name: Force-Deploy-Jagirdar

on:
  push:
    branches: ["main"]  # Jab bhi tum main branch mein kuch dalo ye chalega

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps: deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'  # Ye sari files ko uthayega

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
